"""Added Something

Revision ID: 2b2c7f46060f
Revises: 6e8e1de168b6
Create Date: 2024-11-13 09:25:07.088435

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2b2c7f46060f"
down_revision = "6e8e1de168b6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_transaction_id"), "transaction", ["id"], unique=False)
    op.add_column("user", sa.Column("transaction_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_user_transaction_id"), "user", ["transaction_id"], unique=True
    )
    op.create_foreign_key(None, "user", "transaction", ["transaction_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_index(op.f("ix_user_transaction_id"), table_name="user")
    op.drop_column("user", "transaction_id")
    op.drop_index(op.f("ix_transaction_id"), table_name="transaction")
    op.drop_table("transaction")
    # ### end Alembic commands ###
